# Exported from Render on 2026-02-01T12:35:21Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: pov_flask_prototype
      runtime: python
      repo: https://github.com/Wangadeveloper/pov_flask_prototype
      plan: free
      envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FLASK_ENV
        sync: false
      region: frankfurt
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn "app:app"
      autoDeployTrigger: commit
